# SPDX-FileCopyrightText: 2020 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: AGPL-3.0-only

################################### Default Configuration ############################

baseurl = "https://hedgedoc.org/"
title = "HedgeDoc - Collaborative markdown editor"

# post excert
summarylength = "20"

# google analytics
googleAnalytics = "" # Ex: UA-123-45

# disable language
disableLanguages = [] # disable language from here

enableRobotsTXT = true

###################################### Navigation ######################################

# homepage section menu
[[menu.main]]
name = "Demo"
URL = "https://demo.hedgedoc.org"
weight = 1

[[menu.main]]
name = "Docs"
URL = "https://docs.hedgedoc.org"
weight = 2

[[menu.main]]
name = "Source Code"
URL = "https://git.hedgedoc.org"
weight = 4

[[menu.main]]
name = "Forum"
URL = "https://community.hedgedoc.org"
weight = 5

[[menu.main]]
name = "Matrix"
URL = "https://chat.hedgedoc.org"
weight = 6

[[menu.main]]
name = "FAQ"
URL = "/faq/"
weight = 7

# footer menu
[[menu.footer]]
name = "Source Code"
URL = "https://git.hedgedoc.org"
weight = 1

[[menu.footer]]
name = "Team"
URL = "/team/"
weight = 2

[[menu.footer]]
name = "Help translating"
URL = "https://translate.hedgedoc.org"
weight = 3

[[menu.footer]]
name = "Mastodon"
URL = "https://social.hedgedoc.org"
weight = 4

[[menu.footer]]
name = "Privacy Policy"
URL = "/privacy-policy/"
weight = 5

########################### Default parameters ##########################

[params]
logo = "images/banner/hedgedoc_banner_color_horizontal.svg"
logo_width = "100px"
logo_height = "25px"

# Meta data
description = "The best platform to write and share markdown."
author = "The HedgeDoc developers"

################################### English language #####################################

[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

# copyright
copyright = "The HedgeDoc developers. Made with ❤️ and Hugo. Theme based on [vex-hugo](https://github.com/themefisher/vex-hugo)."

[markup.goldmark.renderer]
unsafe= true